[project]
name = "secbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "chainlit>=1.1.404",
    "openai>=1.45.0",
    "pyproject-toml>=0.0.10",
    "python-dotenv>=1.0.1",
    "ruff>=0.6.5",
]
